add route for search, show empty results page on initial route
VadimZaporozhets/react-movies pull request #6
Opened 2019-05-07 08:59 UTC by VadimZaporozhets

add route for search, show empty results page on initial route, replace webpack-dev-server with express, add 404 page for no-match routes

2019-05-07 09:15 UTC, burnerx47 requested changes

2019-05-07 09:15 UTC, mikerudenko commented on package.json
> +        "react-router-dom": "^4.4.0-beta.8",
As a rule, don't use beta versions in prod, but for this project it's ok

2019-05-07 09:15 UTC, mikerudenko commented on src/App.jsx
> +                            <Route component={PageNotFound} />
please, add Redirect also

2019-05-07 09:15 UTC, mikerudenko commented on src/Home/Home.test.js
> +            push: jest.fn(),
why you need push there?

2019-05-07 09:15 UTC, mikerudenko commented on src/Home/store/Movies/tests/movies.reducer.test.js
> +        console.log(expect.any(Object));
log

2019-05-07 09:15 UTC, mikerudenko commented on src/Home/store/Movies/tests/movies.reducer.test.js
> +        const moviesObj = {
```suggestion
        const moviesPayload = {
```

2019-05-07 09:15 UTC, mikerudenko commented on src/Home/SearchPanel/SearchInputSubmit/SearchInputSubmit.jsx
> +        const finalRoute = routes.SEARCH.replace(
should be separated in routerFormatter.js

2019-05-07 09:15 UTC, mikerudenko commented on src/Home/store/Movies/tests/movies.reducer.test.js
> +            { ...initialState, ...moviesObj },
Please, don't use naming like someArr, or moviesObj

2019-05-07 09:15 UTC, mikerudenko commented on src/store/router.saga.js
>      if (detailsMatch) {
while the app will grow this method will become larger. I suggest you to split this logic. Need to be discussed.

2019-05-07 09:15 UTC, mikerudenko commented on src/store/router.saga.test.js
> +    it('should dispatch clearMovies on home route match', () => {
```suggestion
    it('should dispatch clear moview action on home route match', () => {
```

2019-05-07 09:15 UTC, mikerudenko commented on src/store/store.js
> +    composeWithDevTools(
should be only in development mode

2019-05-07 09:15 UTC, mikerudenko commented on webpack.config.js
> +    devtool: 'source-map'
should be only in development mode

2019-05-07 09:15 UTC, mikerudenko commented on src/store/store.js
> +    blacklist: ['router'],
👍

2019-05-10 09:58 UTC, burnerx47 approved these changes

2019-05-10 09:58 UTC, mikerudenko commented on src/Home/store/Movies/movies.actions.js
> +const CLEAR_MOVIES = 'CLEAR_MOVIES';
I think constants don't need anymore because you don't use anywhere in the code

2019-05-10 09:58 UTC, mikerudenko commented on src/Home/store/Movies/movies.actions.js
> +export const clearMovies = MoviesFeature.ActionCreator(CLEAR_MOVIES);
```suggestion
export const clearMovies = MoviesFeature.ActionCreator('CLEAR_MOVIES');
```

2019-05-13 10:33 UTC, merged